import = ["/home/leonhrt/.config/alacritty/tokyodark.toml"]

[window]
opacity = 0.9

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Beam"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.2"

[font]
size = 10

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

#[font.bold]
#family = "ZedMono Nerd Font"
#style = "Bold"

#[font.italic]
#family = "ZedMono Nerd Font"
#style = "Italic"

[window.padding]
x = 2
y = 1
