[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#F5E0DC"
magenta = "#F5C2E7"
red = "#F7768E"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#12121e"

[colors.dim]
black = "#313244"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#F5E0DC"
magenta = "#F5C2E7"
red = "#F7768E"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#12121e"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#12121e"

[colors.normal]
black = "#15161E"
blue = "#7AA2F7"
cyan = "#7DCFFF"
green = "#9ECE6A"
magenta = "#F5C2E7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#E0AF68"

[colors.primary]
background = "#12121e"
bright_foreground = "#C0CAF5"
dim_foreground = "#C0CAF5"
foreground = "#C0CAF5"

[colors.search.focused_match]
background = "#F5E0DC"
foreground = "#12121e"

#[colors.search.footer_bar]
#background = "#A6ADC8"
#foreground = "#12121e"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#12121e"

[colors.selection]
background = "#F5E0DC"
text = "#12121e"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#12121e"
